package fr.poulpogaz.jam.stage;

import com.badlogic.gdx.math.Vector2;
import fr.poulpogaz.jam.engine.AABBRotateSupplier;
import fr.poulpogaz.jam.engine.AABBSupplier;
import fr.poulpogaz.jam.engine.CircleSupplier;
import fr.poulpogaz.jam.patterns.TargetMove;
import fr.poulpogaz.jam.patterns.TargetPlayer;

import static fr.poulpogaz.jam.Constants.*;
import static fr.poulpogaz.jam.stage.EnemyScript.Location;

public class Stages {

    private static final float M_8_W = MAP_WIDTH / 8f;
    private static final float M_3_8_W = 3 * MAP_WIDTH / 8f;
    private static final float M_5_8_W = 5 * MAP_WIDTH / 8f;
    private static final float M_7_8_W = 7 * MAP_WIDTH / 8f;

    private static final float M_8_H = MAP_HEIGHT / 8f;
    private static final float M_3_8_H = 3 * MAP_HEIGHT / 8f;
    private static final float M_5_8_H = 5 * MAP_HEIGHT / 8f;
    private static final float M_7_8_H = 7 * MAP_HEIGHT / 8f;

    public static final Stage LEVEL_1;

    static {
        LEVEL_1 = new StageBuilder()
                .setBackground("desert_background.png")

                // enemies
                .enemyBuilder()
                    .setName("sunflower")
                    .setTexture("tileset.png", 0, 0, 32, 32)
                    .setLife(20)
                    .setHitBox(new AABBSupplier(32, 32))
                    .build()
                .enemyBuilder()
                    .setName("mosquito")
                    .setRotateTexture("tileset.png", 32, 0, 32, 32)
                    .setLife(30)
                    .setHitBox(new CircleSupplier(16))
                    .build()

                // bullets
                .subBuilder(PlayerBulletDescriptor.Builder::new)
                    .setName(PLAYER_BULLET_NAME)
                    .setRotateTexture("tileset.png", 32, 96, 10, 3)
                    .setHitBoxSupplier(new AABBRotateSupplier(10, 3))
                    .build()
                .bulletBuilder()
                    .setName("sunflower_bullet")
                    .setTexture("tileset.png", 2, 66, 12, 12)
                    .setDamage(1)
                    .setHitBoxSupplier(new CircleSupplier(6))
                    .build()

                // enemies
                .scriptBuilder("sunflower")
                    .setStartPos(0, Location.TOP)
                    .setTriggerTimeS(0)
                    .addBulletPattern(0, new TargetPlayer("sunflower_bullet", 60))
                    .build()

                .scriptBuilder("sunflower")
                    .setStartPos(M_Q_WIDTH, Location.TOP)
                    .setTriggerTimeS(5)
                    .addBulletPattern(0, new TargetPlayer("sunflower_bullet", 60))
                    .build()
                .scriptBuilder("sunflower")
                    .setStartPos(-M_Q_WIDTH, Location.TOP)
                    .setTriggerTimeS(5)
                    .addBulletPattern(0, new TargetPlayer("sunflower_bullet", 60))
                    .build()

                .scriptBuilder("sunflower")
                    .setStartPos(-M_Q_WIDTH, Location.TOP)
                    .setTriggerTimeS(16)
                    .addBulletPattern(0, new TargetPlayer("sunflower_bullet", 60))
                    .build()
                .scriptBuilder("sunflower")
                    .setStartPos(-M_3_8_W, Location.TOP)
                    .setTriggerTimeS(16)
                    .addBulletPattern(0, new TargetPlayer("sunflower_bullet", 60))
                    .build()
                .scriptBuilder("sunflower")
                    .setStartPos(M_3_8_W, Location.TOP)
                    .setTriggerTimeS(16)
                    .addBulletPattern(0, new TargetPlayer("sunflower_bullet", 60))
                    .build()
                .scriptBuilder("sunflower")
                    .setStartPos(M_Q_WIDTH, Location.TOP)
                    .setTriggerTimeS(16)
                    .addBulletPattern(0, new TargetPlayer("sunflower_bullet", 60))
                    .build()

                .scriptBuilder("mosquito")
                    .setStartPos(0, Location.LEFT)
                    .setTriggerTimeS(26)
                    .moveTo(new Vector2(-M_3_8_W, M_7_8_H), 20) // M_8_W, M_7_8_H), 10)
                    .wait(60)
                    .addLastMove(new TargetMove.Player(8))
                    .build()
                .scriptBuilder("mosquito")
                    .setStartPos(20, Location.LEFT)
                    .setTriggerTimeS(26)
                    .moveTo(new Vector2(-M_3_8_W, M_7_8_H - 40), 20) // M_8_W, M_7_8_H), 10)
                    .wait(60)
                    .addLastMove(new TargetMove.Player(8))
                    .build()
                .scriptBuilder("mosquito")
                    .setStartPos(40, Location.LEFT)
                    .setTriggerTimeS(26)
                    .moveTo(new Vector2(-M_3_8_W, M_7_8_H - 60), 20) // M_8_W, M_7_8_H), 10)
                    .wait(60)
                    .addLastMove(new TargetMove.Player(8))
                    .build()
                .scriptBuilder("mosquito")
                    .setStartPos(60, Location.LEFT)
                    .setTriggerTimeS(26)
                    .moveTo(new Vector2(-M_3_8_W, M_7_8_H - 80), 20) // M_8_W, M_7_8_H), 10)
                    .wait(60)
                    .addLastMove(new TargetMove.Player(8))
                    .build()


                .scriptBuilder("mosquito")
                    .setStartPos(0, Location.LEFT)
                    .setTriggerTimeS(29)
                    .moveTo(new Vector2(M_3_8_W, M_7_8_H), 20) // M_8_W, M_7_8_H), 10)
                    .wait(60)
                    .addLastMove(new TargetMove.Player(8))
                    .build()
                .scriptBuilder("mosquito")
                    .setStartPos(20, Location.LEFT)
                    .setTriggerTimeS(29)
                    .moveTo(new Vector2(M_3_8_W, M_7_8_H - 40), 20) // M_8_W, M_7_8_H), 10)
                    .wait(60)
                    .addLastMove(new TargetMove.Player(8))
                    .build()
                .scriptBuilder("mosquito")
                    .setStartPos(40, Location.LEFT)
                    .setTriggerTimeS(29)
                    .moveTo(new Vector2(M_3_8_W, M_7_8_H - 60), 20) // M_8_W, M_7_8_H), 10)
                    .wait(60)
                    .addLastMove(new TargetMove.Player(8))
                    .build()
                .scriptBuilder("mosquito")
                    .setStartPos(60, Location.LEFT)
                    .setTriggerTimeS(29)
                    .moveTo(new Vector2(M_3_8_W, M_7_8_H - 80), 20) // M_8_W, M_7_8_H), 10)
                    .wait(60)
                    .addLastMove(new TargetMove.Player(8))
                    .build()


                .scriptBuilder("mosquito")
                    .setStartPos(0, Location.LEFT)
                    .setTriggerTimeS(32)
                    .moveTo(new Vector2(-M_3_8_W, M_7_8_H), 20) // M_8_W, M_7_8_H), 10)
                    .wait(60)
                    .addLastMove(new TargetMove.Player(8))
                    .build()
                .scriptBuilder("mosquito")
                    .setStartPos(20, Location.LEFT)
                    .setTriggerTimeS(32)
                    .moveTo(new Vector2(-M_3_8_W, M_7_8_H - 40), 20) // M_8_W, M_7_8_H), 10)
                    .wait(60)
                    .addLastMove(new TargetMove.Player(8))
                    .build()
                .scriptBuilder("mosquito")
                    .setStartPos(40, Location.LEFT)
                    .setTriggerTimeS(32)
                    .moveTo(new Vector2(-M_3_8_W, M_7_8_H - 60), 20) // M_8_W, M_7_8_H), 10)
                    .wait(60)
                    .addLastMove(new TargetMove.Player(8))
                    .build()
                .scriptBuilder("mosquito")
                    .setStartPos(60, Location.LEFT)
                    .setTriggerTimeS(32)
                    .moveTo(new Vector2(-M_3_8_W, M_7_8_H - 80), 20) // M_8_W, M_7_8_H), 10)
                    .wait(60)
                    .addLastMove(new TargetMove.Player(8))
                    .build()
                .scriptBuilder("mosquito")
                    .setStartPos(0, Location.LEFT)
                    .setTriggerTimeS(32)
                    .moveTo(new Vector2(M_3_8_W, M_7_8_H), 20) // M_8_W, M_7_8_H), 10)
                    .wait(60)
                    .addLastMove(new TargetMove.Player(8))
                    .build()
                .scriptBuilder("mosquito")
                    .setStartPos(20, Location.LEFT)
                    .setTriggerTimeS(32)
                    .moveTo(new Vector2(M_3_8_W, M_7_8_H - 40), 20) // M_8_W, M_7_8_H), 10)
                    .wait(60)
                    .addLastMove(new TargetMove.Player(8))
                    .build()
                .scriptBuilder("mosquito")
                    .setStartPos(40, Location.LEFT)
                    .setTriggerTimeS(32)
                    .moveTo(new Vector2(M_3_8_W, M_7_8_H - 60), 20) // M_8_W, M_7_8_H), 10)
                    .wait(60)
                    .addLastMove(new TargetMove.Player(8))
                    .build()
                .scriptBuilder("mosquito")
                    .setStartPos(60, Location.LEFT)
                    .setTriggerTimeS(32)
                    .moveTo(new Vector2(M_3_8_W, M_7_8_H - 80), 20) // M_8_W, M_7_8_H), 10)
                    .wait(60)
                    .addLastMove(new TargetMove.Player(8))
                    .build()

                .scriptBuilder("sunflower")
                    .setStartPos(-M_Q_WIDTH, Location.TOP)
                    .setTriggerTimeS(36)
                    .addBulletPattern(0, new TargetPlayer("sunflower_bullet", 60))
                    .build()
                .scriptBuilder("sunflower")
                    .setStartPos(-M_3_8_W, Location.TOP)
                    .setTriggerTimeS(36)
                    .addBulletPattern(0, new TargetPlayer("sunflower_bullet", 60))
                    .build()
                .scriptBuilder("sunflower")
                    .setStartPos(M_3_8_W, Location.TOP)
                    .setTriggerTimeS(36)
                    .addBulletPattern(0, new TargetPlayer("sunflower_bullet", 60))
                    .build()
                .scriptBuilder("sunflower")
                    .setStartPos(M_Q_WIDTH, Location.TOP)
                    .setTriggerTimeS(36)
                    .addBulletPattern(0, new TargetPlayer("sunflower_bullet", 60))
                    .build()

                .scriptBuilder("mosquito")
                    .setStartPos(0, Location.LEFT)
                    .setTriggerTimeS(36)
                    .moveTo(new Vector2(-M_3_8_W, M_7_8_H), 20) // M_8_W, M_7_8_H), 10)
                    .wait(90)
                    .addLastMove(new TargetMove.Player(8))
                    .build()
                .scriptBuilder("mosquito")
                    .setStartPos(20, Location.LEFT)
                    .setTriggerTimeS(36)
                    .moveTo(new Vector2(-M_3_8_W, M_7_8_H - 40), 20) // M_8_W, M_7_8_H), 10)
                    .wait(90)
                    .addLastMove(new TargetMove.Player(8))
                    .build()
                .scriptBuilder("mosquito")
                    .setStartPos(40, Location.LEFT)
                    .setTriggerTimeS(36)
                    .moveTo(new Vector2(-M_3_8_W, M_7_8_H - 60), 20) // M_8_W, M_7_8_H), 10)
                    .wait(90)
                    .addLastMove(new TargetMove.Player(8))
                    .build()
                .scriptBuilder("mosquito")
                    .setStartPos(60, Location.LEFT)
                    .setTriggerTimeS(36)
                    .moveTo(new Vector2(-M_3_8_W, M_7_8_H - 80), 20) // M_8_W, M_7_8_H), 10)
                    .wait(90)
                    .addLastMove(new TargetMove.Player(8))
                    .build()
                .scriptBuilder("mosquito")
                    .setStartPos(0, Location.LEFT)
                    .setTriggerTimeS(36)
                    .moveTo(new Vector2(M_3_8_W, M_7_8_H), 20) // M_8_W, M_7_8_H), 10)
                    .wait(90)
                    .addLastMove(new TargetMove.Player(8))
                    .build()
                .scriptBuilder("mosquito")
                    .setStartPos(20, Location.LEFT)
                    .setTriggerTimeS(36)
                    .moveTo(new Vector2(M_3_8_W, M_7_8_H - 40), 20) // M_8_W, M_7_8_H), 10)
                    .wait(90)
                    .addLastMove(new TargetMove.Player(8))
                    .build()
                .scriptBuilder("mosquito")
                    .setStartPos(40, Location.LEFT)
                    .setTriggerTimeS(36)
                    .moveTo(new Vector2(M_3_8_W, M_7_8_H - 60), 20) // M_8_W, M_7_8_H), 10)
                    .wait(90)
                    .addLastMove(new TargetMove.Player(8))
                    .build()
                .scriptBuilder("mosquito")
                    .setStartPos(60, Location.LEFT)
                    .setTriggerTimeS(36)
                    .moveTo(new Vector2(M_3_8_W, M_7_8_H - 80), 20) // M_8_W, M_7_8_H), 10)
                    .wait(90)
                    .addLastMove(new TargetMove.Player(8))
                    .build()

                .build();
    }
}
